apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azureblob-nfs-ozari-logs
provisioner: blob.csi.azure.com
parameters:
  protocol: nfs
  skuName: Standard_LRS
  containerName: mysql-logs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
