apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-backup
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: backup-azureblob-nfs-ozari
  volumeMode: Filesystem
